### ISSUE TITLE
Client.prepareTransfer() only tries first (IPV6) strategy then fails on system ETIMEDOUT error

### ISSUE THREAD

**Issue by dlear** [patrickjuchli/basic-ftp#133]
**Description**
I am trying to list files from a server with an IPV4 address.  With the 'list()' operation, the code eventually enters `Client.prepareTransfer()` which in turn tries to connect with two strategies: IPV6 then IPV4.  However I'm getting an ETIMEDOUT error when attempting the IPV6 connection (not suprising), but then the code re-throws this error *rather than trying the next strategy (IPV4)*.  You see this here:

```javascript
ftp.log("Trying to find optimal transfer strategy...");
for (const strategy of strategies) {
	try {
		const res = await strategy(ftp);
		ftp.log("Optimal transfer strategy found.");
		this.prepareTransfer = strategy; // eslint-disable-line require-atomic-updates
		return res;
	}
	catch (err) {
		// Receiving an FTPError means that the last transfer strategy failed and we should
		// try the next one. Any other exception should stop the evaluation of strategies because
		// something else went wrong.
		if (!(err instanceof FtpContext_1.FTPError)) {
			throw err;
		}
	}
}
```
Could this `catch` be an empty block or explicitly test for ETIMEOUT?

**Example code**
```javascript
// -- main ----------------------------

const main = async function()
{
	const client = new ftp.Client(CONFIG.get('ftp.timeout'));
	client.ftp.verbose = true;

	await client.access(
	{
		host: CONFIG.get('ftp.host'),
		user: CONFIG.get('ftp.user'),
		password: CONFIG.get('ftp.password'),
		secure: false
	});

	console.log(await client.cd('/VDOT Sites'));
	console.log(await client.list());

	if (!client.closed)
	{
		await client.close();
	}
};

main().catch((err) =>
{
	let msg = err.message;
	if (err.details !== undefined) msg += ' : ' + err.details;
	console.log(msg);
	process.exit(1);
});
```

**Console output**
```
Login security: No encryption
> USER ****
< 331 Password required for ****
> PASS ###
< 230 Logged on
> TYPE I
< 200 Type set to I
> STRU F
< 200 Using file structure 'File'
> OPTS UTF8 ON
< 202 UTF8 mode is always enabled. No need to send this command.
> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
< 200 MLST OPTS type;size;modify;
> CWD /VDOT Sites
< 250 CWD successful. "/VDOT Sites" is current directory.
{
  code: 250,
  message: '250 CWD successful. "/VDOT Sites" is current directory.'
}
Trying to find optimal transfer strategy...
> EPSV
< 229 Entering Extended Passive Mode (|||10034|)
Can't open data connection in passive mode: connect ETIMEDOUT ***.170.37.65:10034
```
**Which version of Node.js are you using?**
Node v12.16.1 with basic-ftp v4.5.3

**Additional context**
If I only attempt the IPV4 strategy (```enterPassiveModeIPv4```) by modifying the ```Client``` constructor, everything then works.

Aside: Also can you swap the order of the strategies (i.e. IPV4 before IPV6) as that would be faster as I suspect many more connections are attempted on IPV4?

**Comment by patrickjuchli** [comment]
The client tries to establish a connection using EPSV first, then if that fails it will try PASV. EPSV is not necessarily IPv6, it's just another command to establish a data connection. 

Looking at the logs, the client first tries EPSV...

```
Trying to find optimal transfer strategy...
> EPSV
< 229 Entering Extended Passive Mode (|||10034|)
```

...which works, the server answers by offering a port. It is using IPv6-style when specifying the port but on the next line you see that the client uses IPv4 to connect to it. And this is what fails:

```
Can't open data connection in passive mode: connect ETIMEDOUT ***.170.37.65:10034
```

It is using IPv4 because that's apparently what your Node runtime decides to do in your context. Which is still the normal thing in most cases.

So you have a timeout when establishing a IPv4 connection to another port of your FTP server. Is this port reachable? Is there a firewall in place that maybe hasn't been configured for this?

**Comment by dlear** [comment]
OK. My diagnosis of my issue is probably wrong or misleading.  However if I change the order of the strategies in the ```Client``` constructor everything works for me:
```javascript
constructor(timeout = 30000) {
	/**
	 * Multiple commands to retrieve a directory listing are possible. This instance
	 * will try all of them in the order presented the first time a directory listing
	 * is requested. After that, `availableListCommands` will  hold only the first
	 * entry that worked.
	 */
	this.availableListCommands = ["MLSD", "LIST -a", "LIST"];
	this.ftp = new FtpContext_1.FTPContext(timeout);
	// this.prepareTransfer = this._enterFirstCompatibleMode([transfer_1.enterPassiveModeIPv6, transfer_1.enterPassiveModeIPv4]); <-- Was
	this.prepareTransfer = this._enterFirstCompatibleMode([transfer_1.enterPassiveModeIPv4, transfer_1.enterPassiveModeIPv6]);
	this.parseList = parseList_1.parseList;
	this._progressTracker = new ProgressTracker_1.ProgressTracker();
}
```
I'm sure there are no firewall issues (I checked the logs), and it works with the change above.
With that change I now get:
```
Connected to **.170.37.65:21
Login security: No encryption
> USER ****
< 331 Password required for ****
> PASS ###
< 230 Logged on
> TYPE I
< 200 Type set to I
> STRU F
< 200 Using file structure 'File'
> OPTS UTF8 ON
< 202 UTF8 mode is always enabled. No need to send this command.
> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
< 200 MLST OPTS type;size;modify;
> CWD /VDOT Sites
< 250 CWD successful. "/VDOT Sites" is current directory.
Trying to find optimal transfer strategy...
> PASV
< 227 Entering Passive Mode (13,82,41,185,78,75)
Optimal transfer strategy found.
> MLSD
< 150 Opening data channel for directory listing of "/VDOT Sites"
Downloading from 13.82.41.185:20043 (No encryption)
< 226 Successfully transferred "/VDOT Sites"
...
```

**Comment by patrickjuchli** [comment]
Ah, I see the reason now. Very interesting!

Your data connection points to a different IP than the control connection. FTP uses two different socket connections, one for general commands and another one for transferring data (upload, download, directory listing). Usually these point to the same IP but the original FTP protocol also considered the use-case we see here: That the data connection is pointing to another machine. Is this the case here? Can you share more of your context?

This has been used very rarely though. Which is why the EPSV command, the more modern variant of PASV, which is used to establish such a data connection, doesn't allow it anymore. That's why only PASV works in your case.

You don't have to overwrite the library for this. Use the following lines to force your client to use, well, PASV. Turns out the name of `enterPassiveModeIPv4` is not so great considering what I've just explained. It should be enterPassiveModePASV.

```
const ftp = require("basic-ftp")

client.prepareTransfer = ftp.enterPassiveModeIPv4
```

**Comment by dlear** [comment]
Thank you for your speedy response.  Your suggestion works.

[I'm accessing this server on behalf of a customer - I've no knowledge of how their FTP server is configured.]

Please close this issue.  (Perhaps rename it to something more useful for others e.g. "Is it possible to force PASV mode for servers where the data connection points to a different IP than the control connection"?)

**Comment by tiagotmr** [comment]
hello how do i change the 

const ftp = require("basic-ftp")

client.prepareTransfer = ftp.enterPassiveModeIPv4

on: 
  push:
      branches:
      - master

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2 

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir:  ./app/
        server-dir: public_html/teste/app/
