### ISSUE TITLE
Additional breaking lines after upload

### ISSUE THREAD

**Issue by xnerhu** [patrickjuchli/basic-ftp#134]
**Describe the bug**
Hello! I've encountered a bug with uploading a plain text file. It adds a breaking line per every line in the original file.

**Example code**
```ts
import { Client as FtpClient } from 'basic-ftp';

(async () => {
  const ftpClient = new FtpClient();

  await ftpClient.access({});

  await ftpClient.uploadFrom(
    createReadStream(resolve('static', 'file.txt'), 'utf8'),
    'file.txt',
  );
})();
````

**Local file - the original one**
```
a
b
c
```

**Remote file - after upload**
```
a

b

c

```

**Console output**
```bash
< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 38 of 300 allowed.
220-Local time is now 21:21. Server port: 21.
220-This is a private system - No anonymous login     
220-IPv6 connections are also welcome on this server. 
220 You will be disconnected after 10 minutes of inactivity.
Login security: No encryption
> USER ...
< 331 User ... OK. Password required
> PASS ###
< 230-Your bandwidth usage is restricted
230-OK. Current restricted directory is /
230 Max allowed filesize is 1048576000 bytes
> TYPE I
< 200 TYPE is now 8-bit binary
> STRU F
< 200 F OK
> OPTS UTF8 ON
< 200 OK, UTF-8 enabled
> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
< 200  MLST OPTS type;size;sizd;modify;UNIX.mode;UNIX.uid;UNIX.gid;unique;
Connected!
Trying to find optimal transfer strategy...
> EPSV
< 229 Extended Passive mode OK (|||58389|)
Optimal transfer strategy found.
> STOR file.txt
< 150 Accepted data connection
Uploading to ... (No encryption)
< 226-File successfully transferred
226 0.336 seconds (measured here), 53.52 bytes per second
```

**Which version of Node.js are you using?**
12.2.0

**Additional context**
The example code is enough, but you can also see [qusly-core](https://github.com/qusly/qusly-core/blob/master/src/models/transfer-manager.ts#L77).

**Comment by patrickjuchli** [comment]
How did you look at the remote file after upload? Did you download it again? When you use `ftpClient.size` for the uploaded file, the size differs from the one on your disk?

**Comment by xnerhu** [comment]
I downloaded the remote file using FileZilla. Size of the remote file is the same as the local one.

**Comment by patrickjuchli** [comment]
Sizes are the same which means nothing has been added. By comparing the two files on a binary level you could make sure nothing has been altered.

This library doesn't just introduce newlines. I don't know what's going on in your particular case but I need you to look a bit harder. Otherwise I'm not sure I can help you.

**Comment by xnerhu** [comment]
Alright, I'll check using checksum.

**Comment by xnerhu** [comment]
1) I've uploaded the original file using FileZilla, then downloaded it with FileZilla.
2) I used basic-ftp for the upload and then downloaded it using FileZilla. 
3) I generated a md5 checksum for each file using [this](https://www.microsoft.com/en-us/download/details.aspx?id=11533).

## Text file

- Original `a7a3aa589440aab6c0b733686295b185`
- FileZilla `a7a3aa589440aab6c0b733686295b185`
- Basic-ftp `db57d93bb8a7c92b563a75b78356e4fe`

Then I tried the same for a binary file instead.

## Binary file
- Original  `4f0e7fabb0f37d2840298a38a5f24cff`
- Filezilla `4f0e7fabb0f37d2840298a38a5f24cff`
- Basic-ftp `4f0e7fabb0f37d2840298a38a5f24cff`

Looking at this, you can clearly see, that something is wrong with ASCII transfer in basic-ftp. I should note that I don't use ftps.

**Comment by patrickjuchli** [comment]
In the logs you can see that all FTP transfer is in binary

```
> TYPE I
< 200 TYPE is now 8-bit binary
```

Basic-FTP doesn't differentiate between different kinds of files. I'm a bit suspicious on why exactly line-breaks seem to be a problem. Windows and Unix have different line-breaks. Windows uses CRLF while everyone else does LF. Is this maybe a source of error somewhere?

**Comment by patrickjuchli** [comment]
In FileZilla, what is your setting under Settings>Transfers>FTP:File Type>Default Transfer Type? Possibly "auto"?

Looks like this might be what's happening: https://winscp.net/eng/docs/faq_line_breaks.

Is it possible to attach here the original file and one where linebreaks are duplicated?

**Comment by xnerhu** [comment]
Hello. Yes, I have the transfer option set to `auto`.

[files.zip](https://github.com/patrickjuchli/basic-ftp/files/4307247/files.zip)

**Comment by patrickjuchli** [comment]
When using basic-ftp, you didn't change the transfer type with a `TYPE A` command to ASCII, right? In your example file, the original has the linebreaks CR+LF, while remote.txt has CR+CR+LF.

This library uploads and downloads files in binary mode without altering them. So I don't know where this duplicate linebreak is coming from. Because the transfer is in binary, the issue mentioned in the link I've posted should not be the case here. Since this library is not converting anything, it must be the server. I don't have any other explanation at the moment.

The next interesting thing we could try is you setting the transfer option in Filezilla to binary like this library and see what happens when transferring the file, upload and then download.

**Comment by patrickjuchli** [comment]
To sum up: This library does not alter the content of any files. By default, it transmits using binary transfer mode. 

Originally, FTP is supposed to change file endings of text files according to the OS of the transfer target when using ASCII transfer mode. Today, this is questionable since all editors should be able to handle newline conventions from both Windows and Unix-like OSes. 

This library will not alter file endings. It will not automatically switch to ASCII transfer mode when there is a text file. And it won't alter file endings if the user explicitly switches to ASCII transfer mode.

I'm writing this as documentation of the position this library takes. What has been described here in this issue is a different thing though. Even though this library is not changing anything, text files seem to be different when downloaded. I have to say that I suspect something to be wrong with the FTP server. I suspect that Filezilla does automatically switch to ASCII transfer mode and applies changes to newlines which somehow then works well with the server. But the server apparently can't handle files just being handed to it without any change, possibly with newlines that don't fit the OS the server is running on.

I'll close this issue because I don't really see what I could do besides starting to also edit files in ASCII mode and automatically selecting ASCII mode if there is a text file. And I don't want to do the latter. I find editing files based on the OS of the transfer target an extremely weird thing to do.

I will reconsider if the error describes in this issue is something that happens often enough.

**Comment by patrickjuchli** [comment]
Of course, please do reopen this issue if there is indeed another reason at play where I could fix something.
