### ISSUE TITLE
How does timeout works?

### ISSUE THREAD

**Issue by AxelTerizaki** [patrickjuchli/basic-ftp#15]
Hello :)

I'm running basic-ftp 2.12.2

I'm downloading some large files over ftp with it, and so far it's worked great for my needs. I have however a question about the timeout argument.

I've received one or two complaints from users with poor connections, who regularly got timeouts when downloading from FTP. I noticed the timeout is set to 0 by default, so I tried to set it like this 

```JS
const ftp = new FTP.Client(20000);
```

However, I still got a transfer stuck when I tried to reproduce the issue (by killing my ftp server during the transfer). It just gets stuck and never recovers from this kind of trouble, nor throws any error.

Am I doing something wrong? Thanks in advance for your help.

**Comment by patrickjuchli** [comment]
I can't reproduce this, I get a timeout if I cut off my internet connection during a transfer. What version of Node are you using?

(I also noticed that timeouts are not terribly useful yet: While data is transferred just fine but maybe over a long time, the control connection sits idle and will actually throw a timeout because of this. I will address this in another ticket as it doesn't concern the issue you raised)

**Comment by AxelTerizaki** [comment]
Node 8.11.1

I'll give it another go tomorrow to see if I can reproduce it once again. I tried to because some of my users were complaining the transfers would get stuck forever when their connection had a hiccup. When I tried to reproduce it, I noticed there was a problem indeed.

Maybe taking a look at the whole JS file I wrote would allow you to see a mistake I might have done? 

It's an updater for a database of videos and other files, but the FTP download with progress is for videos.

https://lab.shelter.moe/karaokemugen/karaokemugen-app/blob/430874c048b89cd3eedd30cbf5739d9c692aacc4/src/_updater/karabase_updater.js

I'm calling ftp.download() in the DownloadMedias() function.

**Comment by patrickjuchli** [comment]
There are 3 separate points in this issue, I'll list them so as we don't get confused:

1. If you don't set a timeout (or set it to 0) there will never be a timeout. So the feedback of your users is correct but that's as expected.
2. Setting a timeout should work. This is the issue tracked by this ticket. If you don't get timeouts when setting a short timeout for testing we have to look into this.
3. Setting a 20s timeout is problematic because during a transfer, the control socket connection sits idle and might not do anything for 20s which will trigger a timeout. This is not what most users expect. I have to address this as a separate issue.

So, while point 2 might be working, timeouts might still not be practical for you because of point 3.

**Comment by AxelTerizaki** [comment]
1. The code I showed you is the one in production where there is indeed no timeout. It's when I tried to add one that I noticed it didn't change anything about the issue I had.
1. I agree with this, that's the main focus :)
1. Okay, I understand. I did set it to 20s to try it out in a quick way. The problem is that we're having generally big files (20 to 100 Mb in general) which can take a while on a slow connection... But we can think about that later.

As promised, I'll look into testing it again this evening.

**Comment by patrickjuchli** [comment]
It's probably a good idea to set the default timeout to some other value than 0 as users are apparently not directly aware of this. Something conservative, at least 1 minute.

**Comment by patrickjuchli** [comment]
@AxelTerizaki, there is a new version out, 2.13.0.

The default timeout of 0 has been changed to 30 seconds. The issue around idle control connections during transfers has also been addressed (see #16). This release also includes some minor fixed around timeouts.

I still don't understand why you don't get any timeouts, though. Can you have another look with the new version?

**Comment by AxelTerizaki** [comment]
Hello.

I apologize for not testing like I said I'd do, we had to release a new version of our app and it needed more attention than I thought it would. 

Nice to see there's a new version. I'll update it and see if it works any better tomorrow evening.

**Comment by patrickjuchli** [comment]
I've updated the documentation to better explain what happens after an error or timeout occurs.

https://github.com/patrickjuchli/basic-ftp#timeout--error-handling

**Comment by AxelTerizaki** [comment]
I confirm it is fixed with 2.13.0 ! 

Thank you very much :) I'll close the issue now.
