### ISSUE TITLE
Last modification date

### ISSUE THREAD

**Issue by akermabon** [patrickjuchli/basic-ftp#151]
Hello,

Thank you for this great library, I've been using it in production for a long time now.
However, I've recently had the need to sort files using last modification date value, and I noticed it's either empty, or unusable.
When I log the file content, I get this:

```javascript
FileInfo {
  // trimmed
  rawModifiedAt: 'Jul 02 02:09',
  modifiedAt: undefined,
}
```
I'm using version 4.5.2 (4.x in my package)
As you can see, modifiedAt is empty, and raw value is unusable, because of the missing year :(
I get the correct date in another library (that I won't promote here)

```javascript
{
  // trimmed
  date: 2020-07-02T00:09:00.000Z
}
```

Do you think last modification date parsing can be improved ?
I'd like to be able to switch back to this lib ! 
Thank you !

**Comment by patrickjuchli** [comment]
Parsing modification dates and FTP servers have a long history.

Originally, the FTP command "LIST" is used to retrieve a directory listing. The result of this command was never meant to be machine-readable though. What you get there is exactly the same you get when using ls or dir in the terminal. Every OS looks different and so do different locales.

This library relies on a more modern (2007) command "MLSD". This command has been introduced because of the difficulties around "LIST" and has been designed to be machine-readable. This library relies on MLSD for parsed modification dates. It seems that your server doesn't support the MLSD command.

That's what you see in the fields you mention: `rawModifiedAt` holds the unparsed date coming from the server. It's not "unusable", that's exactly what you get. `modifiedAt` would hold the parsed date which is undefined in your case.

Libraries go to great lengths to still somehow parse dates from the LIST command. This one doesn't. I understand that this might not be acceptable for you. But that's the decision that this library has taken.

(Stay careful when relying on the date parsed by the other library. If this file is from last year and on a Unix system, you won't get the correct time anymore because its place will be taken to specify the year. So instead of 'Jul 02 02:09', there will probably be 'Jul 02 2019'. Or not. Nobody knows, depends entirely on the OS and the specific FTP server.)
