### ISSUE TITLE
simple usage on web server

### ISSUE THREAD

**Issue by p3im4n** [patrickjuchli/basic-ftp#189]
hi
I have an nginx web server and  a vsftpd ftp server  on same ubunto machine.
I test ftp server with filezilla.
I installed nodejs and nmp and basic-ftp successfully but on console I have this errors:

app.js:1 Uncaught ReferenceError: require is not defined
    at app.js:1
(anonymous) @ app.js:1
2app.js:6 Uncaught (in promise) ReferenceError: Cannot access 'ftp' before initialization
    at example (app.js:6)
    at HTMLButtonElement.onclick ((index):9)

and my ftp log is empty too!!

this is a very very  simple usage, 
so  what's the correct usage of basic-ftp??

 index.html:

.
.
< button type="button" onclick="example()" >upload< /button >
<script src="app.js"></script>
.
.
.

app.js:
 
![jssss](https://user-images.githubusercontent.com/49278298/112736599-92172980-8f71-11eb-9c6b-d727d47deced.PNG)

**Comment by patrickjuchli** [comment]
Are you running this in a browser? 

That's not possible, this library is written for Node.js. Browsers don't run Node.js. TCP socket connections required for FTP for example are not possible in browsers due to security restrictions.

You have been asking this question in an another ticket that I've closed, you've posted the same question on other threads. I need to make something very clear now: 

I understand the frustration if something doesn't work, I'm a developer myself. But this issue tracker is not for helping you program your applications. Your issue clearly has nothing to do with this library if already `require` fails. You can't copy-paste your app and scream at people – referring to your exclamation marks – if they don't have time to fix your problem. 

If you do this again I will block you from this board.
