### ISSUE TITLE
Can't connect to localhost ftp

### ISSUE THREAD

**Issue by elpeleq42** [patrickjuchli/basic-ftp#19]
If I try connecting to a local ftp server(created using ftpd, both it and basicftp running on nwjs) it doesn't work, returning this object:
{"code":502,"message":"502 Command not implemented"}

But If I try the exact same using a ftp software or even a chrome extension, it works perfectly

More info I'm a bit lazy to add here:
https://stackoverflow.com/questions/51272734/problems-with-ftpd-server-and-basic-ftp-client-on-nodejs

**Comment by elpeleq42** [comment]
Setting it didn't change the error object, maybe because i'm using nwjs.

Is there another way?

**Comment by patrickjuchli** [comment]
This setting doesn't change the error object but will use `console.log` to log out every communication detail with the FTP server. It will show us what exactly happened before you got the error message.

The error you received (502) is being sent by the FTP server. It doesn't have anything to do with localhost or nwjs. Looking at the console output will let us know which command exactly it doesn't implement.

**Comment by patrickjuchli** [comment]
Do you have problems seeing the console output? Maybe try using only Node.js directly, not nwjs.

**Comment by patrickjuchli** [comment]
@elpeleq42, are you working on resolving this? I'll have to close this ticket without additional information. Let me know your status and what kind of help you need.

**Comment by elpeleq42** [comment]
I really tried, but I can't make nodejs to install npms.

Is there another way to check it?

**Comment by elpeleq42** [comment]
I changed that command to alert instead of console.log the error(so I can see it on nwjs).

It alerted: < 220 FTP server (nodeftpd) ready.
> AUTH TLS
< 502 Command not implemented
Closing sockets.

and the output on my application(which is a console) was the same:
{"code":502,"message":"502 Command not implemented"}

**Comment by elpeleq42** [comment]
If I make secure:false, it returns this:
```
> TYPE I
< 200 OK
> STRU F
< 502 Command not implemented.
Closing sockets.
```
(right after alerting that user passed and password was right)

**Comment by patrickjuchli** [comment]
[RFC 959](https://tools.ietf.org/html/rfc959) is the specification for FTP from 1985. The command `STRU` defines the transfer mode for data and is part of the most basic set of commands. Its default setting is specified under [Minimum Implementation](https://tools.ietf.org/html/rfc959#section-5). It's strange that the FTP server doesn't implement this.

`AUTH TLS` is how the request for secure explicit FTPS begins. Some older servers only understand `AUTH SSL` but if that is the case they should respond with another error message since the command `AUTH` is the same.

What I can do for you here is to show you a more manual way to set up a connection where you can customize the behavior. I suggest you use another FTP server, though. Are you using https://github.com/nodeftpd/nodeftpd? I suggest opening a ticket over there, especially for `STRU`. I will close this ticket because it is moving outside the scope of this library.

```js
const client = new ftp.Client()
// Connect to the FTP server with host and port.
await client.connect("localhost", 21)
// Try upgrading to TLS using an older method. If this is not working, your server doesn't support TLS.
await client.useTLS({}, "AUTH SSL")
// Login with user and password
await client.login("username", "password")
// At least use binary transfer mode
await client.send("TYPE I")
// If TLS worked you can try if these default settings can be applied but I suspect your server doesn't know them.
await client.send("PBSZ 0")
await client.send("PROT P")
...
```
