### ISSUE TITLE
uploadDir fails if a directory already exists, is this the expected behavior?

### ISSUE THREAD

**Issue by medokin** [patrickjuchli/basic-ftp#5]

**Comment by patrickjuchli** [comment]
It is, let me try to explain why.

The main focus of this library is to lay a foundation in such a way that the API is easy to compose (async-await being an example) and to extend. 

The methods that operate on whole directories recursively are a bit of an exception to that focus. You won’t find these included in most FTP libraries as well. I included them anyway because we need to upload or download multiple files and folders most of the time, we rarely operate on a single file.

So their existence is a bit of a compromise already. Their implementation should then stay as simple as possible because the API makes it very easy to write custom variations of them. This behaviour also follows the MKD command itself which also fails if a directory already exists.

Taking one step back could also be helpful: Why do you need such a function? I'm using the following lines most often:

```
ensure(myRemotePath)
clearWorkingDir()
uploadDir(myLocalPath)
```

That way I’m sure what myRemotePath holds. Removing anything before uploading new stuff is a critical step. Not doing that before uploading would be some kind of merge operation where the files I upload will overwrite existing ones but still coexist with other files and folders having a different names. I hope this makes sense.

**Comment by medokin** [comment]
I understand your motivation to not include any overwriting, but it seems like PUT overwrites files by default, that's why I expected a similar behavior for directories.

In my case we upload our JS frontend application and we'd like to keep the old assets (fingerprinted), to avoid any caching issues.

I need to implement this either way, the question where i makes more sense.

**Comment by patrickjuchli** [comment]
Okay, I see.

There's another argument to be made in favour of the feature. Some servers don't report an error if you try to create an existing directory. There, your setup would work. Also, the API composes a bit better if you can use `uploadDir` without having to use `removeDir/cleanWorkingDir` first.

Let's keep this open, have to think a bit.

**Comment by medokin** [comment]
Good point. I did not event know that some servers behave that way.

And as you already mentioned, `uploadDir` is non-standard already, this change surerly adds complexity to the code, but the result would be more fault tolerant.

It's yours to decide, but I don't see any cons. If the directory does not exist, it will be created. If it's already there, that's fine too. There is no need for an error.

**Comment by patrickjuchli** [comment]
In 2.8.0
