### ISSUE TITLE
Question: events?

### ISSUE THREAD

**Issue by warpdesign** [patrickjuchli/basic-ftp#54]
When basic-ftp is connected and I'm not sending any commands, how do I detect events like:
- timeout
- connection with the server lost/closed
etc.. 

I saw no events-related methods in the API.

**Comment by patrickjuchli** [comment]
There are two different questions here. One is how timeouts are handled in this library, the other one how errors are handled generally and in the case of "when not doing anything".

## Timeout

A connection timeout is only tracked while you're actively doing something. Why should there be a timeout when you are not waiting for anything? Timeouts are used to signal broken connections because there is no other way to know if a connection is broken. People invented timeouts to make a decision: After 30 seconds of no response, let's assume something is broken. This might be wrong, maybe the connection is just really slow. But we make the decision to not care anymore. We declare the connection as dead, which is why the `Client` instance closes and can't be used anymore. You'll have to instantiate a new one. (Why? Because while we declare "timeout", it's still possible that the response will arrive eventually. And when it does we won't be expecting it.)

## Error reporting in general

In this library, any error is reported as an exception. That implies: As an exception raised while doing something. The advantage of that is that I can handle the error close to the code that maybe caused it. But, as you correctly observed, what happens if for example the connection has been closed by the server while you're **not** doing anything? In this case, there is no context in which to catch an error, how do you know about it?

Then, this library will tell you about it the **next time** you try to do something. An exception will be raised and it'll say something like: Client has been closed because: Connection has been closed.

## Bigger picture

There is a similar thinking behind both topics: Why care about something you're not using at the moment? We have been talking a bit about existing clients like FileZilla – if you observe their logs they're doing exactly the same thing: If a connection is gone, they only reconnect as soon as you do something again.

That way, you only have to handle errors in one way. If I were to introduce error events, you'd have 2 different places where errors pop up.

**Comment by patrickjuchli** [comment]
`FTPContext` can help you understand the behaviour further. Here is how error handlers are setup internally: https://github.com/patrickjuchli/basic-ftp/blob/bc3d03c424ea2b9ee89ac1d6cb1c2394927a4863/src/FtpContext.ts#L303-L314

"Doing something" means having a `Task` being handled. Each time such a task is submitted we check if the client is actually still open: https://github.com/patrickjuchli/basic-ftp/blob/bc3d03c424ea2b9ee89ac1d6cb1c2394927a4863/src/FtpContext.ts#L237-L244

**Comment by warpdesign** [comment]
Thanks for the detailed explanation. I see why it has been implemented like this.

That said I want to give some feedback to the user in case the connection has been lost. I guess calling regularly the `NOOP` FTP command should do the trick.
