### ISSUE TITLE
Suggestion: access should disconnect automatically on failure

### ISSUE THREAD

**Issue by warpdesign** [patrickjuchli/basic-ftp#56]
I think `access` should automatically disconnect the client, allowing later calls to `access` to work. As it is right now, after a failed call to `access` the user has either to create a new client, or manually call `login` in order to access the FTP.

See: https://github.com/patrickjuchli/basic-ftp/issues/55

**Comment by patrickjuchli** [comment]
I agree but I think there is more confusion hidden here:

If I provided the wrong password, I get an FTPError which means I can continue using the client. If I provided the wrong address, I get a socket error which will make the client unusable.

That's not great. I think the client should never become unusable after `access` or `connect`. Both methods are kind of a "soft" (re-)initalization. The best approach would have been to make these methods static methods that return a valid `Client` instance. But having them as methods means it should be possible to call them several times.

**Comment by patrickjuchli** [comment]
So here is what's gonna happen:

`connect` and thus by extension `access` essentially reset a `Client` instance. You can call them multiple times and each time a completely new control connection will attempt to connect/reconnect to the server. You will also be able to reopen a Client that has been closed due to an error with both of these methods.

This achieves multiple things:

- It solves your specific issue with retrying `access` after wrong credentials.
- These retries work the same way when there was a network or any other error.
- It keeps the API backwards-compatible
- It also introduces the nice side-effect of being able to continue to use the same Client instance after any error by simply reconnecting.

**Comment by warpdesign** [comment]
Sounds good to me!

**Comment by patrickjuchli** [comment]
In 3.4.0
