### ISSUE TITLE
Add a way to configure the FtpContext's encoding

### ISSUE THREAD

**Issue by warpdesign** [patrickjuchli/basic-ftp#59]
FtpContext's constructor has an encoding parameter which allows to set the encoding used when decoding results such as the LIST command result but there's no way to change its default value since the Client constructor simply calls:

```js
class Client {
    constructor(timeout = 30000) {
        this.ftp = new FTPContext(timeout)
    }
}
```

I suggest adding a new encoding to the Client's constructor that defaults to `"utf8"`:

```js
class Client {
    constructor(timeout = 30000, encoding="utf8") {
        this.ftp = new FTPContext(timeout, encoding)
    }
}
```

**Comment by patrickjuchli** [comment]
You can already use `client.ftp.encoding`, see the [README](https://github.com/patrickjuchli/basic-ftp#ftpcontext).

I don't want to expose this further because it's not something you should typically change. Also, Node.js only supports "latin" as a viable alternative here.

**Comment by warpdesign** [comment]
Some servers only use iso/latin encoding. Without changing the encoding
this would make basic-ftp return wrong filenames. Instead of poking into
the ftp properties I'd rather want to set it when creating the client.

Le sam. 23 févr. 2019 à 13:08, Patrick Juchli <notifications@github.com> a
écrit :

**Comment by patrickjuchli** [comment]
First, it's not poking when it's documented in the README.

Second, FTP servers by standard are to use ASCII aka Latin1. And UTF-8 has the nice property of being backwards compatible with ASCII. So no, you won't get wrong filenames. https://en.wikipedia.org/wiki/UTF-8.

Third, this topic can indeed be more complicated but not with Latin1. People/servers did use other encodings, maybe they still do, but this was never a standard and it's impossible to find out for a client which encoding is being used. That's why you definitely should never do that. This library could offer support for arbitrary encodings but I have decided against that. UTF-8 is fine in most cases.

More info for example here: https://wiki.filezilla-project.org/Character_Encoding

**Comment by warpdesign** [comment]
No it's not: UTF8 is backwards compatible with ASCII standard table only.

Latin 1 (also known as ISO8859-1) is an *extension* to ASCII and any characters in that table aren't compatible with UTF8 so you will get errors when interpreting Latin1 text as UTF8 if it contains special characters.

For example, this is a Latin1 encoded file isn't properly displayed if charset is set to UTF8:
 - [latin1](https://www.warpdesign.fr/tests/test.html)
 - same file displayed using [utf8](https://www.warpdesign.fr/tests/test-utf.html)

**Comment by patrickjuchli** [comment]
Thanks for the correction! I won't change the API though, sorry.

**Comment by Kreijstal** [comment]
welp I need to search for another ftp library then

**Comment by patrickjuchli** [comment]
Setting `client.ftp.encoding` doesn't help?

**Comment by patrickjuchli** [comment]
For future reference, after instantiating the client and connecting to the server you can do this:

```js
client.ftp.encoding = "latin1" // will use that encoding for commands and file listings
await client.send("OPTS UTF-8 OFF")
```

That these two are linked has been discussed here, #168. I can address this at some point but I don't see a need to change the API.
