### ISSUE TITLE
Abort the current data transfer 

### ISSUE THREAD

**Issue by xnerhu** [patrickjuchli/basic-ftp#68]
Hello. What's **the best way to abort the current data transfer**. Currently I am doing something like this: 
- At some moment when I am uploading an file to my server I send `ABOR` command by `client.send()`. I get an error like this _`User launched a task
while another one is still running. Forgot to use 'await' or '.then()'?`_
- So I set `client.ftp.task = undefined` and I get _`write ECONNRESET (data socket)`_ error.
- I fix it by destroying the dataSocket `client.ftp.dataSocket.destroy()`.
- It seems ok, but when I am getting the size of an file by `client.size()` I got another error _`451-Transfer aborted\n451 0.501
seconds (measured here), 31.92 Kbytes per second`_. The workaround is to wait e.g. 10ms and then trigger `client.getSize()`.

I think I am doing it the wrong way.

```ts
import { createWriteStream, createReadStream, statSync } from 'fs';
import { resolve } from 'path';
import { Client } from 'basic-ftp';

const fileName = 'file.rar';
const path = resolve("uploads", fileName);
let client: Client;
let aborted = false;

async function abort() {
  (client.ftp as any).task = undefined;
  client.ftp.dataSocket.destroy();
  
  console.log(await client.send("ABOR", true));  // { code: 426, message: '426 Transfer aborted' }
}

async function progressHandler(info) {
  if (info.bytes > 262144 && !aborted) {
    aborted = true;
    await abort();

    const sizeRes = await client.size(fileName); // <---------------------- The problem
    console.log(sizeRes); // FTPError: 451-Transfer aborted 451
  }
}

async function init() {
  client = new Client();
  await client.access(ftpConfig);

  client.trackProgress(progressHandler);

  const uploadRes = await client.upload(createReadStream(path), fileName);
  console.log(uploadRes); // Unreachable code
}

init();
```

**Comment by patrickjuchli** [comment]
The best way to abort a transfer with this FTP library is by simply closing the client. You should not set `ftp.task`, you are reaching into internal components. That's why you get all these other errors.

As an experiment, you can try using `client.ftp.send("ABOR")`: Use the `send` function of the FTPContext, not the client. That could maybe work.

**Comment by xnerhu** [comment]
Thank you for response. I will check how it works.

**Comment by patrickjuchli** [comment]
Does it work?

**Comment by xnerhu** [comment]
Unfortunately  `client.ftp.send("ABOR")` doesn't work. I get `User closed client during task`.
Now I am aborting just by restarting client but I need also to unpipe Writable from `client.ftp.dataSocket` and everything works .

**Comment by patrickjuchli** [comment]
Okay, then let's keep this open. I don't have time right now to have a look but it might be something the library could support in the future.

**Comment by xnerhu** [comment]
Yeah that would be very awesome. I have another question, when I am e.g downloading I can't e.g. list a directory because of `User launched a task while another one is still running. Forgot to use 'await' or '.then()'?`. This is very annoying. I think the workaround here would be a second instance of `Client`.

**Comment by patrickjuchli** [comment]
The FTP protocol always works with request-response, maybe multiple responses to a request. But it doesn't support concurrent requests, something like requestA,requestB,responseB,responseA. That's why you can't do what you describe above, it wouldn't work anyway.

Using a second instance is the correct solution. This is also what you would do to allow multiple uploads at the same time.

**Comment by xnerhu** [comment]
Thank you very much for your help.

**Comment by patrickjuchli** [comment]
Two things: Sending `ABOR` doesn't remove a partially uploaded file. And any form of cancellation will result in an exception anyway because the user wants to exit the current execution context.

There isn't any advantage to just disconnect the client. I'll close this ticket.

FTP itself doesn't give any transactional/atomic guarantees – if a connection drops during transfer, the partially uploaded file will be regarded as complete. To add such guarantees (including retries, check of file size at the end, etc.) would be a good fit for an external library using `basic-ftp` underneath.

**Comment by xnerhu** [comment]
Great idea @patrickjuchli. I'll think about implementing it in my [Qusly-core](https://www.github.com/qusly/qusly-core).
