### ISSUE TITLE
client.upload() should handle src stream 'error' events

### ISSUE THREAD

**Issue by nahuel** [patrickjuchli/basic-ftp#78]
If you do the following:

```javascript
const src = fs.createReadStream('/this/file/doesnt/exists')
await client.upload(src, "myfile")
```

The `src` stream will fail emitting an `'error'` event. If you didn't registered a `process.on('uncaughtException',...)` handler the entire node process will be killed, because basic-ftp doesn't registers for src `'error'` events. If, instead, you registered it, then the `'error'` event will be caught in that custom handler but `await client.upload(...)` will block until a data transfer timeout error is raised.

I think the sane thing to do is to make basic-ftp register for src `'error'` events and reject the `upload()` promise if one is emitted.

**Comment by patrickjuchli** [comment]
Yes, something similar should be done for download and destination streams.

**Comment by patrickjuchli** [comment]
In 3.7.0

**Comment by nahuel** [comment]
This fix also handles the case were the error is raised after some data is correctly read and transferred from src, signalling the server the transfer is being aborted? Or you need to close the ftp connection and restart it after the error?

**Comment by patrickjuchli** [comment]
The error event of a stream should lead to the same result during a transfer. "Should" because there is no unit test for that at the moment but I can change that.

The Promise will be rejected and any connection (data and control) to the server will be closed. This behaviour is the same for any error except for official FTP error responses from the server. You can reopen the connection with `access`.

One note: There is no special signal being sent to the server other than closing of all connections. That means that you'll have a partially uploaded file on the server.
