### ISSUE TITLE
Wildcarding download?

### ISSUE THREAD

**Issue by vrmerlin** [patrickjuchli/basic-ftp#79]
I successfully wrote a script that downloads all the file in a directory, using:

```client.downloadDir("/foo/bar")```

However, what I really want to do is:

 ```client.downloadDir("/foo/bar/20190624*.gz")```

where I can wildcard the files pulled.

Is there a way to do that? The command line wget suports it.

**Comment by patrickjuchli** [comment]
No, there is no way to do that. There are also no plans to implement this because this library focuses on basic functionality specific to FTP. Wildcards or glob patterns are not specific to FTP.

The method `downloadDir` is quite simple and it should be possible for you to implement a custom one with wildcards: https://github.com/patrickjuchli/basic-ftp/blob/b5bd1b7dd1db17b5653331a27ce1c643faa379f6/src/Client.ts#L459-L473
