### ISSUE TITLE
List -a throws 550 error

### ISSUE THREAD

**Issue by cschindl** [patrickjuchli/basic-ftp#91]
**Describe the bug**
Since the pull request (https://github.com/patrickjuchli/basic-ftp/pull/29), the parameter "-a" has always been included by default when listing directories. This unfortunately throws a 550 error on some FTP servers, because they do not understand the command (https://github.com/h3imdall/ftp-remote-edit/issues/328).

**Example code**
https://github.com/h3imdall/ftp-remote-edit/blob/a7d4f360b8f81101740ee05b02af0b516099c379/lib/connectors/ftp.js#L95

**Console output**
https://github.com/h3imdall/ftp-remote-edit/issues/328#issuecomment-524096516
Unfortunately the screenshot of the ftp log is still missing. This will hopefully be handed in later.

**Which version of Node.js are you using?**
v10.2.0

**Additional context**
The parameter "-a" should not be passed by default. Is it possible to set it as a parameter for the "list" function?

**Comment by patrickjuchli** [comment]
There are a few problems with -a. It’s not a standard, it may or may not have an influence on listing, it may cause an error or not.

Still, it needs to be considered for methods like removeDir. If not all files are removed from a directory because some have not been listed without -a, the directory itself can’t be removed. 

So this business with -a is not an option or a feature but a problem. It’s not just “show hidden files”, it’s more messy than that. That’s why I don’t want to pass this problem onto users but solve it here.

We could do the same thing as we do for PASV/EPSV: The library just tries listing with -a the first time and if it doesn’t work it will continue without it for all subsequent calls. This test can then include MLSD (a better list command) in the future as well.

**Comment by cschindl** [comment]
Hi @patrickjuchli,

thank you for your quick feedback. The idea with trying out and using the function without parameters in case of failure sounds good. That would help me a lot. Can you implement it or do you need help?

**Comment by patrickjuchli** [comment]
This is somewhat similar to what I'm doing with PASV/EPSV and I want to have a look if this is an opportunity to refactor things a bit. I can have a look.

**Comment by cschindl** [comment]
Sounds good to me. Here is the FTP log, which is still missing. https://github.com/h3imdall/ftp-remote-edit/issues/328#issuecomment-525440708

**Comment by patrickjuchli** [comment]
In 3.8.2
